apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: security-team-role
  #namespace: default
  namespace: security-team
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list