apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: security-team
  labels:
    run: cnspec
  name: cnspec
spec:
  serviceAccountName: security-team-serviceaccount
  automountServiceAccountToken: false
  volumes:
    - hostPath: 
        path: /
      name: root
  containers:
  - command:
    - sleep
    - "7200"
    image: hrouhan/cnspec
    name: cnspec
    volumeMounts:
      - name: root
        mountPath: /mnt/host
        readOnly: true
