apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: security-team-roleBinding
  namespace: security-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: security-team-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default